== General rules and best practices for Service Accounts

* A default service account is automatically created for each namespace.
* Service accounts can be added when required. Each pod is associated with exactly one service account but multiple pods can use the same service account.
* A pod can only use one service account from the same namespace.
* Service accounts are assigned to a pod by specifying the account’s name in the pod manifest. If you don’t assign it explicitly the pod will use the default service account.
* The default permissions for a service account don't allow it to list or modify any resources. The default service account isn't allowed to view cluster state let alone modify it in any way.
* By default, the default service account in a namespace has no permissions other than those of an unauthenticated user.
* Therefore pods by default can’t even view cluster state. Its up to you to grant them appropriate permissions to do that via one or more ClusterRoleBindings.
* Giving all your service accounts the clusteradmin ClusterRole is a bad idea. It is best to give everyone only the permissions they need to do their job and not a single permission more.
* It’s a good idea to create a specific service account for each pod and then associate it with a tailor-made role or a ClusterRole through a RoleBinding.
* If one of your pods only needs to read pods while the other also needs to modify them then create two different service accounts and make those pods use them by specifying the serviceaccountName property in the pod spec.

== General concepts around Cluster Roles and Cluster Role Bindings

* All of the default cluster roles and rolebindings are labeled with kubernetes.io/bootstrapping=rbac-defaults

https://v1-16.docs.kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings

